package group27.landRegistration.users;

import group27.landRegistration.nonUsers.*;
import group27.landRegistration.utility.FileManager;

import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;

public class Auditor extends User {

    public Auditor(String name, String password, String email, String gender, long NID, long phoneNumber, LocalDate doB) {
        super(name, password, email, gender, NID, phoneNumber, doB);
    }


    public List<SystemActivityLog> viewSystemActivity() {
        FileManager<SystemActivityLog> fm = new FileManager<>("SystemActivity.dat");
        return fm.loadList();
    }


    public void flagSystemActivity(SystemActivityLog log) {
        // Update local object
        log.setFlagged(true);

        // Update file
        FileManager<SystemActivityLog> fm = new FileManager<>("SystemActivity.dat");
        List<SystemActivityLog> logs = fm.loadList();

        for (int i = 0; i < logs.size(); i++) {
            if (logs.get(i).getLogID() == log.getLogID()) {
                SystemActivityLog existing = logs.get(i);
                existing.setFlagged(true);
                logs.set(i, existing);
                break;
            }
        }
        fm.saveList(logs);
    }


    public String generateIntegrityReport(int year) {
        FileManager<SystemActivityLog> fm = new FileManager<>("SystemActivity.dat");
        List<SystemActivityLog> logs = fm.loadList();

        int totalActivities = 0;
        int flaggedActivities = 0;
        StringBuilder flaggedDetails = new StringBuilder();

        for (SystemActivityLog log : logs) {
            if (log.getTimestamp().getYear() == year) {
                totalActivities++;
                if (log.isFlagged()) {
                    flaggedActivities++;
                    flaggedDetails.append(String.format(" - [ID: %d] User %d: %s\n",
                            log.getLogID(), log.getUserID(), log.getAction()));
                }
            }
        }

        return String.format(
                "========================================\n" +
                        "      ANNUAL INTEGRITY SUMMARY: %d      \n" +
                        "========================================\n\n" +
                        "Generated By: Auditor %s (ID: %d)\n" +
                        "Date: %s\n\n" +
                        "STATISTICS:\n" +
                        "----------------------------------------\n" +
                        "Total System Activities Recorded: %d\n" +
                        "Total Suspicious Flags Raised:    %d\n" +
                        "----------------------------------------\n\n" +
                        "FLAGGED ACTIVITY DETAILS:\n%s\n" +
                        "========================================\n",
                year, this.getName(), this.getUserID(), LocalDate.now(),
                totalActivities, flaggedActivities,
                (flaggedDetails.length() > 0 ? flaggedDetails.toString() : " No flagged activities found.")
        );
    }


    public void saveReportToDatabase(String content, String type) {
        Report report = new Report(
                this.getUserID(),
                type,
                "Internal",
                content,
                LocalDate.now()
        );
        FileManager<Report> fm = new FileManager<>("Report.dat");
        fm.appendItem(report);
    }

    public List<Application> getApprovedApplications() {
        FileManager<Application> fm = new FileManager<>("Application.dat");
        return fm.loadList().stream()
                .filter(app -> "Approved".equalsIgnoreCase(app.getStatus()))
                .collect(Collectors.toList());
    }


    public void flagApplicationForReview(Application app, String reason) {
        app.addNote("[AUDITOR FLAG]: " + reason);

        FileManager<Application> fm = new FileManager<>("Application.dat");
        List<Application> apps = fm.loadList();

        for (int i = 0; i < apps.size(); i++) {
            if (apps.get(i).getApplicationID() == app.getApplicationID()) {
                apps.set(i, app);
                break;
            }
        }
        fm.saveList(apps);
    }


    public String generateCustomAuditReport(LocalDate startDate, LocalDate endDate) {
        FileManager<SystemActivityLog> fm = new FileManager<>("SystemActivity.dat");
        List<SystemActivityLog> logs = fm.loadList();

        StringBuilder reportBuilder = new StringBuilder();
        reportBuilder.append("CUSTOM AUDIT REPORT\n");
        reportBuilder.append("Period: ").append(startDate).append(" TO ").append(endDate).append("\n\n");

        int totalCount = 0;
        int flagCount = 0;
        StringBuilder details = new StringBuilder();

        for (SystemActivityLog log : logs) {
            LocalDate logDate = log.getTimestamp().toLocalDate();

            if ((logDate.isEqual(startDate) || logDate.isAfter(startDate)) &&
                    (logDate.isEqual(endDate) || logDate.isBefore(endDate))) {

                totalCount++;
                if (log.isFlagged()) flagCount++;

                details.append(String.format("[%s] User %d: %s %s\n",
                        log.getFormattedTimestamp(), log.getUserID(), log.getAction(),
                        (log.isFlagged() ? "[FLAGGED]" : "")));
            }
        }

        reportBuilder.append("Total: ").append(totalCount).append(" | Flagged: ").append(flagCount).append("\n\n");
        reportBuilder.append(details);
        return reportBuilder.toString();
    }


    public List<MonthlyReport> getAllMonthlyReports() {
        FileManager<MonthlyReport> fm = new FileManager<>("MonthlyReport.dat");
        return fm.loadList();
    }

    public void lockMonthlyReport(MonthlyReport report) {
        report.setStatus("Locked");

        FileManager<MonthlyReport> fm = new FileManager<>("MonthlyReport.dat");
        List<MonthlyReport> list = fm.loadList();

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getReportID() == report.getReportID()) {
                list.set(i, report);
                break;
            }
        }
        fm.saveList(list);
    }


    public List<User> getAllSystemUsers() {
        FileManager<User> fm = new FileManager<>("users.dat");
        return fm.loadList();
    }

    public List<UserPermission> getPermissionsForUser(int userID) {
        FileManager<UserPermission> fm = new FileManager<>("UserPermissions.dat");
        List<UserPermission> allPerms = fm.loadList();

        return allPerms.stream()
                .filter(p -> p.getUserID() == userID)
                .collect(Collectors.toList());
    }

    public void markPermissionForReview(UserPermission perm) {
        perm.setFlaggedForReview(true);

        FileManager<UserPermission> fm = new FileManager<>("UserPermissions.dat");
        List<UserPermission> list = fm.loadList();

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getPermissionID() == perm.getPermissionID()) {
                list.set(i, perm);
                break;
            }
        }
        fm.saveList(list);
    }
    public List<Plot> getAllPlots() {
        FileManager<Plot> fm = new FileManager<>("Plot.dat");
        return fm.loadList();
    }


    public String getPlotCertificationStatus(int plotID) {
        FileManager<Certificate> fm = new FileManager<>("Certificate.dat");
        List<Certificate> certs = fm.loadList();

        return "Check System"; // Placeholder if deep linking is unavailable, or:
        // You can implement the deep link if you load Applications and Certificates together.
    }


    public void flagPlotValuation(Plot plot, String reason) {
        // We use the plot's survey log to store the audit flag
        plot.addSurveyLog("[AUDITOR FLAG] Valuation Issue: " + reason);

        FileManager<Plot> fm = new FileManager<>("Plot.dat");
        List<Plot> plots = fm.loadList();

        for (int i = 0; i < plots.size(); i++) {
            if (plots.get(i).getPlotID() == plot.getPlotID()) {
                plots.set(i, plot);
                break;
            }
        }
        fm.saveList(plots);
    }
}