package group27.landRegistration.users;

import group27.landRegistration.nonUsers.*;
import group27.landRegistration.utility.FileManager;

import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;

public class Auditor extends User {

    public Auditor(String name, String password, String email, String gender, long NID, long phoneNumber, LocalDate doB) {
        super(name, password, email, gender, NID, phoneNumber, doB);
    }


    public List<SystemActivityLog> viewSystemActivity() {
        FileManager<SystemActivityLog> fm = new FileManager<>("SystemActivity.dat");
        return fm.loadList();
    }


    public void flagSystemActivity(SystemActivityLog log) {
        // Update local object
        log.setFlagged(true);

        // Update file
        FileManager<SystemActivityLog> fm = new FileManager<>("SystemActivity.dat");
        List<SystemActivityLog> logs = fm.loadList();

        for (int i = 0; i < logs.size(); i++) {
            if (logs.get(i).getLogID() == log.getLogID()) {
                SystemActivityLog existing = logs.get(i);
                existing.setFlagged(true);
                logs.set(i, existing);
                break;
            }
        }
        fm.saveList(logs);
    }


    public String generateIntegrityReport(int year) {
        FileManager<SystemActivityLog> fm = new FileManager<>("SystemActivity.dat");
        List<SystemActivityLog> logs = fm.loadList();

        int totalActivities = 0;
        int flaggedActivities = 0;
        StringBuilder flaggedDetails = new StringBuilder();

        for (SystemActivityLog log : logs) {
            if (log.getTimestamp().getYear() == year) {
                totalActivities++;
                if (log.isFlagged()) {
                    flaggedActivities++;
                    flaggedDetails.append(String.format(" - [ID: %d] User %d: %s\n",
                            log.getLogID(), log.getUserID(), log.getAction()));
                }
            }
        }

        return String.format(
                "========================================\n" +
                        "      ANNUAL INTEGRITY SUMMARY: %d      \n" +
                        "========================================\n\n" +
                        "Generated By: Auditor %s (ID: %d)\n" +
                        "Date: %s\n\n" +
                        "STATISTICS:\n" +
                        "----------------------------------------\n" +
                        "Total System Activities Recorded: %d\n" +
                        "Total Suspicious Flags Raised:    %d\n" +
                        "----------------------------------------\n\n" +
                        "FLAGGED ACTIVITY DETAILS:\n%s\n" +
                        "========================================\n",
                year, this.getName(), this.getUserID(), LocalDate.now(),
                totalActivities, flaggedActivities,
                (flaggedDetails.length() > 0 ? flaggedDetails.toString() : " No flagged activities found.")
        );
    }


    public void saveReportToDatabase(String content, String type) {
        // Requires Report.java class
        Report report = new Report(
                this.getUserID(),
                type,
                "Internal",
                content,
                LocalDate.now()
        );
        FileManager<Report> fm = new FileManager<>("Report.dat");
        fm.appendItem(report);
    }

    public List<Application> getApprovedApplications() {
        FileManager<Application> fm = new FileManager<>("Application.dat");
        return fm.loadList().stream()
                .filter(app -> "Approved".equalsIgnoreCase(app.getStatus()))
                .collect(Collectors.toList());
    }


    public void flagApplicationForReview(Application app, String reason) {
        app.addNote("[AUDITOR FLAG]: " + reason);

        FileManager<Application> fm = new FileManager<>("Application.dat");
        List<Application> apps = fm.loadList();

        for (int i = 0; i < apps.size(); i++) {
            if (apps.get(i).getApplicationID() == app.getApplicationID()) {
                apps.set(i, app);
                break;
            }
        }
        fm.saveList(apps);
    }


    public String generateCustomAuditReport(LocalDate startDate, LocalDate endDate) {
        FileManager<SystemActivityLog> fm = new FileManager<>("SystemActivity.dat");
        List<SystemActivityLog> logs = fm.loadList();

        StringBuilder reportBuilder = new StringBuilder();
        reportBuilder.append("CUSTOM AUDIT REPORT\n");
        reportBuilder.append("Period: ").append(startDate).append(" TO ").append(endDate).append("\n\n");

        int totalCount = 0;
        int flagCount = 0;
        StringBuilder details = new StringBuilder();

        for (SystemActivityLog log : logs) {
            LocalDate logDate = log.getTimestamp().toLocalDate();

            if ((logDate.isEqual(startDate) || logDate.isAfter(startDate)) &&
                    (logDate.isEqual(endDate) || logDate.isBefore(endDate))) {

                totalCount++;
                if (log.isFlagged()) flagCount++;

                details.append(String.format("[%s] User %d: %s %s\n",
                        log.getFormattedTimestamp(), log.getUserID(), log.getAction(),
                        (log.isFlagged() ? "[FLAGGED]" : "")));
            }
        }

        reportBuilder.append("Total: ").append(totalCount).append(" | Flagged: ").append(flagCount).append("\n\n");
        reportBuilder.append(details);
        return reportBuilder.toString();
    }


    public List<MonthlyReport> getAllMonthlyReports() {
        // Requires MonthlyReport.java
        FileManager<MonthlyReport> fm = new FileManager<>("MonthlyReport.dat");
        return fm.loadList();
    }

    public void lockMonthlyReport(MonthlyReport report) {
        report.setStatus("Locked");

        FileManager<MonthlyReport> fm = new FileManager<>("MonthlyReport.dat");
        List<MonthlyReport> list = fm.loadList();

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getReportID() == report.getReportID()) {
                list.set(i, report);
                break;
            }
        }
        fm.saveList(list);
    }


    public List<User> getAllSystemUsers() {
        FileManager<User> fm = new FileManager<>("users.dat");
        return fm.loadList();
    }


    public void markPermissionForReview(group27.landRegistration.nonUsers.UserPermission perm) {
        // 1. Update the Permission File
        perm.setFlaggedForReview(true);

        FileManager<group27.landRegistration.nonUsers.UserPermission> fm =
                new FileManager<>("UserPermissions.dat");
        List<group27.landRegistration.nonUsers.UserPermission> list = fm.loadList();

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getPermissionID() == perm.getPermissionID()) {
                list.set(i, perm);
                break;
            }
        }
        fm.saveList(list);


        group27.landRegistration.nonUsers.SystemActivityLog logEntry =
                new group27.landRegistration.nonUsers.SystemActivityLog(
                        0, // ID will be auto-generated by static block logic
                        this.getUserID(),
                        "Flagged Permission ID " + perm.getPermissionID() + " for User " + perm.getUserID()
                );

        // Mark the log itself as flagged so it counts towards the "Suspicious Flags" stat
        logEntry.setFlagged(true);

        FileManager<group27.landRegistration.nonUsers.SystemActivityLog> logFM =
                new FileManager<>("SystemActivity.dat");
        logFM.appendItem(logEntry);
    }

    public List<Plot> getAllPlots() {
        FileManager<Plot> fm = new FileManager<>("Plot.dat");
        return fm.loadList();
    }


    public String getPlotCertificationStatus(int plotID) {
        // Requires Certificate.java
        FileManager<Certificate> fm = new FileManager<>("Certificate.dat");
        List<Certificate> certs = fm.loadList();

        return "Check System";
    }


    public void flagPlotValuation(Plot plot, String reason) {
        // We use the plot's survey log to store the audit flag
        plot.addSurveyLog("[AUDITOR FLAG] Valuation Issue: " + reason);

        FileManager<Plot> fm = new FileManager<>("Plot.dat");
        List<Plot> plots = fm.loadList();

        for (int i = 0; i < plots.size(); i++) {
            if (plots.get(i).getPlotID() == plot.getPlotID()) {
                plots.set(i, plot);
                break;
            }
        }
        fm.saveList(plots);
    }
    public List<UserPermission> getPermissionsForUser(int userID) {
        FileManager<UserPermission> fm = new FileManager<>("UserPermissions.dat");
        List<UserPermission> allPerms = fm.loadList();

        // 1. Try to find existing permissions
        List<UserPermission> userPerms = allPerms.stream()
                .filter(p -> p.getUserID() == userID)
                .collect(Collectors.toList());

        // 2. SELF-HEALING: If no permissions exist for this user, generate defaults
        if (userPerms.isEmpty()) {
            int nextPid = (allPerms.isEmpty()) ? 1 : allPerms.get(allPerms.size() - 1).getPermissionID() + 1;

            // Add default permissions so the table is never empty
            UserPermission p1 = new UserPermission(nextPid++, userID, "General Access", "Login", "Basic");
            UserPermission p2 = new UserPermission(nextPid++, userID, "Dashboard", "View Data", "Read-Only");
            UserPermission p3 = new UserPermission(nextPid++, userID, "Profile", "Edit", "Medium");

            userPerms.add(p1);
            userPerms.add(p2);
            userPerms.add(p3);

            // Save these new defaults to the file permanently
            allPerms.addAll(userPerms);
            fm.saveList(allPerms);
        }

        return userPerms;
    }

    public java.util.Map<String, Integer> getApplicationStats(String filterType) {
        FileManager<Application> fm = new FileManager<>("Application.dat");
        List<Application> apps = fm.loadList();

        // Initialize counters
        java.util.Map<String, Integer> stats = new java.util.HashMap<>();
        stats.put("Approved", 0);
        stats.put("Rejected", 0);
        stats.put("Pending", 0);

        LocalDate now = LocalDate.now();

        for (Application app : apps) {
            // Use dateUpdated if available (decision date), otherwise dateSubmitted
            LocalDate appDate = app.getDateUpdated();
            if (appDate == null) appDate = app.getDateSubmitted();

            boolean include = false;

            // Filter Logic
            if ("All Time".equals(filterType)) {
                include = true;
            } else if ("This Year".equals(filterType)) {
                if (appDate.getYear() == now.getYear()) include = true;
            } else if ("This Month".equals(filterType)) {
                if (appDate.getYear() == now.getYear() && appDate.getMonth() == now.getMonth()) include = true;
            }

            // Count Logic
            if (include) {
                String status = app.getStatus();
                if ("Approved".equalsIgnoreCase(status)) {
                    stats.put("Approved", stats.get("Approved") + 1);
                } else if ("Rejected".equalsIgnoreCase(status)) {
                    stats.put("Rejected", stats.get("Rejected") + 1);
                } else {
                    stats.put("Pending", stats.get("Pending") + 1);
                }
            }
        }
        return stats;
    }

    // --- FIXED METHOD: Uses correct constructor and Setters for dates ---
    public void generateDummyApplications() {
        FileManager<Application> fm = new FileManager<>("Application.dat");
        List<Application> apps = new java.util.ArrayList<>();
        LocalDate now = LocalDate.now();

        // 1. Create Application using the valid 4-argument constructor
        // 2. Use setters to manually adjust dates for history simulation

        // Approved #1
        Application a1 = new Application(101, 1003, "Approved", "All good");
        a1.setDateSubmitted(now.minusDays(5));
        a1.setDateUpdated(now);
        apps.add(a1);

        // Approved #2
        Application a2 = new Application(102, 1003, "Approved", "Verified");
        a2.setDateSubmitted(now.minusMonths(1));
        a2.setDateUpdated(now.minusWeeks(3));
        apps.add(a2);

        // Approved #3
        Application a3 = new Application(103, 1004, "Approved", "Done");
        a3.setDateSubmitted(now.minusMonths(2));
        a3.setDateUpdated(now.minusMonths(2));
        apps.add(a3);

        // Rejected #1
        Application a4 = new Application(104, 1004, "Rejected", "Invalid docs");
        a4.setDateSubmitted(now.minusDays(2));
        a4.setDateUpdated(now);
        apps.add(a4);

        // Rejected #2
        Application a5 = new Application(105, 1003, "Rejected", "Dispute found");
        a5.setDateSubmitted(now.minusDays(10));
        a5.setDateUpdated(now.minusDays(1));
        apps.add(a5);

        // Pending
        apps.add(new Application(106, 1005, "Pending", "Reviewing"));
        apps.add(new Application(107, 1005, "Pending", "Waiting"));
        apps.add(new Application(108, 1005, "Pending", "New"));
        apps.add(new Application(109, 1005, "Pending", "New"));

        fm.saveList(apps);
    }
}