package group27.landRegistration.controllers.BankRepresentativeGoals;

import group27.landRegistration.nonUsers.Application;
import group27.landRegistration.nonUsers.SystemActivityLog;
import group27.landRegistration.users.User;
import group27.landRegistration.utility.CurrentPageLoader;
import group27.landRegistration.utility.CustomAlert;
import group27.landRegistration.utility.FileManager;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.TextField;

import java.util.List;

public class RefundViewController {

    private User loggedInUser;

    @FXML
    private TextField Amounttextfield;
    @FXML
    private TextField ApplicationIdTextField;

    public void setUserData(User user) {
        this.loggedInUser = user;
    }

    public User getLoggedInUser(){
        return loggedInUser;
    }

    @FXML
    public void SubmitOnAction(ActionEvent actionEvent) {
        // 1. Validation
        if (Amounttextfield.getText().isEmpty() || ApplicationIdTextField.getText().isEmpty()) {
            CustomAlert.show(Alert.AlertType.ERROR, "Validation Error", "Missing Fields", "Please enter both Application ID and Amount.");
            return;
        }

        int appId;
        double amount;

        try {
            appId = Integer.parseInt(ApplicationIdTextField.getText());
            amount = Double.parseDouble(Amounttextfield.getText());
        } catch (NumberFormatException e) {
            CustomAlert.show(Alert.AlertType.ERROR, "Validation Error", "Invalid Input", "Application ID must be an integer and Amount must be a number.");
            return;
        }

        // 2. Load Applications
        FileManager<Application> appFM = new FileManager<>("Application.dat");
        List<Application> apps = appFM.loadList();

        Application targetApp = null;
        int targetIndex = -1;

        // 3. Find the Application
        for (int i = 0; i < apps.size(); i++) {
            if (apps.get(i).getApplicationID() == appId) {
                targetApp = apps.get(i);
                targetIndex = i;
                break;
            }
        }

        if (targetApp == null) {
            CustomAlert.show(Alert.AlertType.ERROR, "Not Found", "Application Missing", "No application found with ID: " + appId);
            return;
        }

        // 4. Process Refund Logic
        // We typically only refund if rejected or cancelled, but for this goal we assume manual override.
        targetApp.setStatus("Refunded");
        targetApp.addNote("Refund of " + amount + " BDT processed by " + loggedInUser.getName() + " (ID: " + loggedInUser.getUserID() + ")");

        // Update the list
        apps.set(targetIndex, targetApp);
        appFM.saveList(apps);

        // 5. Log the Activity
        FileManager<SystemActivityLog> logFM = new FileManager<>("SystemActivity.dat");
        // ID is auto-generated by the SystemActivityLog constructor/static block
        SystemActivityLog log = new SystemActivityLog(0, loggedInUser.getUserID(), "Processed Refund for App #" + appId + ": " + amount + " BDT");
        logFM.appendItem(log);

        // 6. Success & Navigate
        CustomAlert.show(Alert.AlertType.INFORMATION, "Success", "Refund Processed", "The refund has been recorded and application status updated.");
        GoBackOnAction(actionEvent);
    }

    @FXML
    public void GoBackOnAction(ActionEvent actionEvent) {
        try {
            CurrentPageLoader page = new CurrentPageLoader();

            page.loadWithData(
                    "/group27/landRegistration/AllDashboards/BankRepresentativeDashboardView.fxml",
                    actionEvent,
                    controller -> {
                        try {
                            controller.getClass()
                                    .getMethod("setUserData", User.class)
                                    .invoke(controller, loggedInUser);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
            );
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}