package group27.landRegistration.controllers.BankRepresentativeGoals;

import group27.landRegistration.nonUsers.PaymentSlip;
import group27.landRegistration.nonUsers.SystemActivityLog;
import group27.landRegistration.users.User;
import group27.landRegistration.utility.CurrentPageLoader;
import group27.landRegistration.utility.CustomAlert;
import group27.landRegistration.utility.FileManager;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;

import java.util.List;

public class SendPaymentNoticeviewcontroller {

    private User loggedInUser;

    @FXML
    private ComboBox<String> NotificationTypeComboBox;
    @FXML
    private TextField TransactionIDTextField;

    public void setUserData(User user) {
        this.loggedInUser = user;
    }

    public User getLoggedInUser(){
        return loggedInUser;
    }

    @FXML
    private void initialize() {
        // Populate the combo box with standard notice types
        NotificationTypeComboBox.setItems(FXCollections.observableArrayList(
                "Payment Received Confirmation",
                "Payment Overdue Warning",
                "Insufficient Funds Notice",
                "Transaction Rejected",
                "Clarification Request"
        ));
    }

    @FXML
    public void SubmitOnAction(ActionEvent actionEvent) {
        // 1. Validation
        String transIdText = TransactionIDTextField.getText();
        String noticeType = NotificationTypeComboBox.getValue();

        if (transIdText == null || transIdText.trim().isEmpty() || noticeType == null) {
            CustomAlert.show(Alert.AlertType.ERROR, "Input Error", "Missing Fields", "Please enter a Transaction ID and select a Notice Type.");
            return;
        }

        int transactionID;
        try {
            transactionID = Integer.parseInt(transIdText);
        } catch (NumberFormatException e) {
            CustomAlert.show(Alert.AlertType.ERROR, "Input Error", "Invalid ID", "Transaction ID must be a numeric value.");
            return;
        }

        // 2. Verify Transaction Exists
        FileManager<PaymentSlip> slipFM = new FileManager<>("PaymentSlip.dat");
        List<PaymentSlip> slips = slipFM.loadList();

        PaymentSlip foundSlip = null;
        for (PaymentSlip slip : slips) {
            if (slip.getTransactionID() == transactionID) {
                foundSlip = slip;
                break;
            }
        }

        if (foundSlip == null) {
            CustomAlert.show(Alert.AlertType.ERROR, "Not Found", "Invalid Transaction", "No payment slip found with Transaction ID: " + transactionID);
            return;
        }

        // 3. Log the Notice (Simulates sending the actual notice)
        FileManager<SystemActivityLog> logFM = new FileManager<>("SystemActivity.dat");

        String actionDescription = "Sent Notice [" + noticeType + "] for Transaction ID " + transactionID + " to User " + foundSlip.getOwnerID();

        // ID is auto-generated by constructor/static block logic in SystemActivityLog
        SystemActivityLog log = new SystemActivityLog(0, loggedInUser.getUserID(), actionDescription);
        logFM.appendItem(log);

        // 4. Success Alert and Return
        CustomAlert.show(Alert.AlertType.INFORMATION, "Success", "Notice Sent", "The payment notice has been successfully logged and sent to the user.");
        GoBackOnAction(actionEvent);
    }

    @FXML
    public void GoBackOnAction(ActionEvent actionEvent) {
        try {
            CurrentPageLoader page = new CurrentPageLoader();

            page.loadWithData(
                    "/group27/landRegistration/AllDashboards/BankRepresentativeDashboardView.fxml",
                    actionEvent,
                    controller -> {
                        try {
                            controller.getClass()
                                    .getMethod("setUserData", User.class)
                                    .invoke(controller, loggedInUser);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
            );
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}